# Generated by Django 3.0.7 on 2020-06-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='base.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=2),
        ),
    ]
